# GET http://localhost:5000/api/auth

# POST http://localhost:5000/api/auth/createuser
# Content-Type: application/json

# {
#     "name": "Shakir",
#     "email": "shakir@gmail.com",
#     "password": "123456"
# }

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "shakir@gmail.com",
    "password": "123456"
}

